{% set version = "0.10.6" %}

package:
  name: awk-language-server
  version: {{ version }}

source:
  url: https://registry.npmjs.org/awk-language-server/-/awk-language-server-{{ version }}.tgz
  sha256: 254c12fefe25453846313318fcd5f7b00dcef46568bb02c065a65248a77d3e11

build:
  number: 0
  skip: true  # [win or nodejs != 20]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - nodejs
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - awk-language-server --help

about:
  license: MIT
  license_file: LICENSE
  summary: Language Server for AWK
  home: https://github.com/Beaglefoot/awk-language-server
  dev_url: https://github.com/Beaglefoot/awk-language-server

extra:
  recipe-maintainers:
    - danielnachun
